// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_PROJECT_ID = import.meta.env.VITE_SUPABASE_PROJECT_ID || import.meta.env.SUPABASE_PROJECT_ID;
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  import.meta.env.SUPABASE_URL ||
  (typeof SUPABASE_PROJECT_ID === 'string' && SUPABASE_PROJECT_ID.length > 0
    ? `https://${SUPABASE_PROJECT_ID}.supabase.co`
    : undefined);
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_SUPABASE_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  import.meta.env.SUPABASE_KEY ||
  import.meta.env.SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

function createDisabledClient() {
  const disabledError = { message: 'Supabase is not configured in this environment.' };
  const qb = {
    select: () => qb,
    eq: () => qb,
    in: () => qb,
    maybeSingle: async () => ({ data: null, error: disabledError }),
    insert: async () => ({ data: null, error: disabledError }),
    update: async () => ({ data: null, error: disabledError }),
    delete: async () => ({ data: null, error: disabledError }),
    upsert: async () => ({ data: null, error: disabledError }),
    execute: async () => ({ data: null, error: disabledError }),
  };

  return {
    auth: {
      getSession: async () => ({ data: { session: null }, error: null }),
      getUser: async () => ({ data: { user: null }, error: null }),
      signInWithPassword: async () => ({ data: { user: null, session: null }, error: disabledError }),
      signUp: async () => ({ data: { user: null, session: null }, error: disabledError }),
      signOut: async () => ({ error: null }),
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => undefined } } }),
    },
    from: () => qb,
    functions: {
      invoke: async () => ({ data: null, error: disabledError }),
    },
    storage: {
      from: () => ({
        upload: async () => ({ data: null, error: disabledError }),
      }),
    },
  } as any;
}

const hasSupabaseConfig =
  typeof SUPABASE_URL === 'string' &&
  SUPABASE_URL.length > 0 &&
  typeof SUPABASE_PUBLISHABLE_KEY === 'string' &&
  SUPABASE_PUBLISHABLE_KEY.length > 0;

if (!hasSupabaseConfig) {
  console.warn(
    '[supabase] Missing Supabase URL/key. Expected VITE_SUPABASE_URL (or VITE_SUPABASE_PROJECT_ID) and VITE_SUPABASE_PUBLISHABLE_KEY (or VITE_SUPABASE_ANON_KEY). Running in offline-safe mode.'
  );
}

export const supabase = hasSupabaseConfig
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : createDisabledClient();
